version: '3'

services:
  webapp:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: nginx-php7.4
    hostname: nginx-php7.4
    environment:
      - TZ=Australia/Sydney
    ports:
      - "3000:3000"
    networks:
      - default
    restart: unless-stopped
    working_dir: /var/www/html

networks:
  default: