language: php
php:
  - '5.4'
  - '5.6'
  - '7.0'
env:
  - DB=mysql

before_script:
  - mysql -e 'create database cmfive;'
  - git clone https://github.com/2pisoftware/cmfive-boilerplate ~/cmfive
  - cd ~/cmfive
  - php cmfive.php
