version: 0.0

os: linux

files:
  - source: /
    destination: /var/www/cmfive-boilerplate

hooks:
  BeforeInstall:
    - location: .codepipeline/ec2/before-install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: .codepipeline/ec2/after-install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: .codepipeline/ec2/application-start.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: .codepipeline/ec2/application-stop.sh
      timeout: 300
      runas: root
