version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/cmfive-boilerplate
hooks:
  BeforeInstall:
    - location: scripts/code-deploy/before-install.sh
      timout: 300
      runas: root
  AfterInstall:
    - location: scripts/code-deploy/after-install.sh
      timout: 300
      runas: root
  ApplicationStart:
    - location: scripts/code-deploy/application-start.sh
      timout: 300
      runas: root
  ApplicationStop:
    - location: scripts/code-deploy/application-stop.sh
      timout: 300
      runas: root