---
# -----------------
# database instance
# -----------------
db_instance_port:
    resolvers:
    - local:
        value: "3306"

# -------
# service
# -------
php_version:
    resolvers:
    - local:
        value: "7.2"

php_suffix:
    resolvers:
    - local:
        value: "7.2"

mysql_version:
    resolvers:
    - local:
        value: "5.7.21"

mysql_suffix:
    resolvers:
    - local:
        value: "5.7"