version: '3'

services:
  cmfive:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CMFIVE_CORE_BRANCH: ${CMFIVE_CORE_BRANCH}
    container_name: nginx-php7.4
    hostname: nginx-php7.4
    environment:
      - TZ=Australia/Sydney
    ports:
      - "80:3000"
    networks:
      - default
    restart: unless-stopped
    working_dir: /var/www/html

networks:
  default:
