---
manifest:
  providers:
  - name: dev_profile
    type: local
  resolvers:
  - name: inline
    provider: dev_profile
    type: local

data:
# -----------------
# database instance
# -----------------
- name: db_instance_username
  resolvers:
  - resolver: inline
    prop:
      value: "root"
- name: db_instance_password
  resolvers:
  - resolver: inline
    prop:
      value: "root"
- name: db_instance_port
  resolvers:
  - resolver: inline
    prop:
      value: "3306"
# ----------
# admin user
# ----------
- name: admin_login_username
  resolvers:
  - resolver: inline
    prop:
      value: "cmfive"
- name: admin_login_password
  resolvers:
  - resolver: inline
    prop:
      value: "cmfive"
- name: admin_email
  resolvers:
  - resolver: inline
    prop:
      value: "cmfive@2pisoftware.com"
- name: admin_first_name
  resolvers:
  - resolver: inline
    prop:
      value: "cmfive"
- name: admin_last_name
  resolvers:
  - resolver: inline
    prop:
      value: "cmfive"
# ---------------
# client database
# ---------------
- name: db_username
  resolvers:
  - resolver: inline
    prop:
      value: "cmfive"
- name: db_password
  resolvers:
  - resolver: inline
    prop:
      value: "cmfive"
- name: db_database
  resolvers:
  - resolver: inline
    prop:
      value: "cmfive"
# -------
# service
# -------
- name: php_version
  resolvers:
  - resolver: inline
    prop:
      value: "7.4"
- name: php_suffix
  resolvers:
  - resolver: inline
    prop:
      value: "7.4mployment Type and Holiday entries can be created and deleted
 Test  tests/acceptance/staff_StaffAdminCest.php:runTests
 Step  Click "Add Employment Type"
 Fail  Link or Button or CSS or XPath element with 'Add Employment Type' was not found.

Scenario Steps:

 12. $I->click("Add Employment Type") at tests/_support/Helper/CmfiveStaffModule.php:20
 11. $I->amOnPage("/staff-admin#employmenttypes") at tests/_support/Helper/CmfiveStaffModule.php:19
 10. $I->addEmploymentType("CmfiveUI","staff_employment_ty...",true,"10.00","8") at tests/acceptance/staff_StaffAdminCest.php:19
 9. $I->wait(1) at tests/_support/Helper/CmfiveSite.php:108
 8. $I->click("Login") at tests/_support/Helper/CmfiveSite.php:105
 7. $I->fillField("password","admin") at tests/_support/Helper/CmfiveSite.php:104

Artifacts:

Png: /var/www/html/test/Codeception/tests/_output/StaffAdminCest.runTests.fail.png"
- name: mysql_version
  resolvers:
  - resolver: inline
    prop:
      value: "5.7.21"
- name: mysql_suffix
  resolvers:
  - resolver: inline
    prop:
      value: "5.7"
# -----------
# cmfive core
# -----------
- name: cmfive_core_ref
  resolvers:
  - resolver: inline
    prop:
      value: "feature/config_json"
# -----------
# third party
# -----------
- name: module_configs
  resolvers:
  - resolver: inline
    prop:
      value: {}
  modifiers:
  - modifier: json_serialize
