---
# admin user
admin_email: admin@2pisoftware.com
admin_first_name: cmfive
admin_last_name: cmfive
admin_login_username: cmfive
admin_login_password: cmfive

# database
db_database: cmfive
db_username: cmfive
db_password: cmfive
db_port: '3306'

# services
php_version: '7.2'
php_suffix: '7.2'
mysql_version: '5.7.21'
mysql_suffix: '5.7'