---
manifest:
  providers:
  - name: aws_provider
    type: aws
    prop:
      profile: null
  resolvers:  
  - name: res_s3    
    type: s3
    provider: aws_provider        
    primary: True
    prop:
      format: json
      source:        
        path:
          lookup: environment
          prop:          
            variable: S3_FOLDER
        file:
          lookup: environment
          prop:  
            variable: FILENAME  
  - name: res_sm
    provider: aws_provider
    type: secretsmanager

data:
# -----------------
# database instance
# -----------------
- name: db_instance_username
  resolvers:
  - resolver: res_s3
  - resolver: res_sm
    prop:
      index: username
- name: db_instance_password
  resolvers:
  - resolver: res_s3
  - resolver: res_sm
    prop:
      index: password
- name: db_instance_endpoint
  resolvers:
  - resolver: res_s3
- name: db_instance_port
  resolvers:
  - resolver: res_s3
- name: encryption_key
  resolvers:
  - resolver: res_s3
# ----------
# admin user
# ----------
- name: admin_login_username
  resolvers:
  - resolver: res_s3
  - resolver: res_sm
    prop:
      index: username
- name: admin_login_password   
  resolvers:
  - resolver: res_s3
  - resolver: res_sm
    prop:
      index: password
- name: admin_email
  resolvers:
  - resolver: res_s3
- name: admin_first_name
  resolvers:
  - resolver: res_s3
- name: admin_last_name
  resolvers:
  - resolver: res_s3
# ---------------
# client database
# ---------------
- name: db_username
  resolvers:
  - resolver: res_s3
  - resolver: res_sm
    prop:
      index: username
- name: db_password
  resolvers:
  - resolver: res_s3
  - resolver: res_sm
    prop:
      index: password
- name: db_database
  resolvers:
  - resolver: res_s3
# -------
# service
# -------
- name: php_version
  resolvers:
  - resolver: res_s3
- name: php_suffix
  resolvers:
  - resolver: res_s3
# -----------
# cmfive core
# -----------
- name: cmfive_core_ref
  resolvers:
  - resolver: res_s3
    prop:
      default: "feature/config_json"
# -----------
# third party
# -----------
- name: module_configs
  resolvers:
  - resolver: res_s3
    prop:
      default: {}
  modifiers:
  - modifier: merge
    prop:
      value: {"system": {"encryption": {"key": "{{encryption_key}}"}}} 
  - modifier: substitue
    prop:
      key: encryption_key
  - modifier: json_serialize
# ------
# domain
# ------
- name: base_domain
  resolvers:
  - resolver: res_s3
    prop:
      default: "2piboom.com"
- name: site_name
  resolvers:
  - resolver: res_s3        
- name: site_domains
  resolvers:
  - resolver: res_s3
    prop:
      default: ["www.{{site_name}}.{{base_domain}}", "{{site_name}}.{{base_domain}}"]
  modifiers:
  - modifier: substitue
    prop:
      key: ["base_domain", "site_name"]
  - modifier: json_serialize
- name: certbot_webmaster
  resolvers:
  - resolver: res_s3
    prop:
      default: "webmaster@2pisoftware.com"