---
# -----------------
# database instance
# -----------------
db_instance_username:
    resolvers:
    - "datastore"    
    - "secret"

db_instance_password:
    resolvers:
    - "datastore"    
    - "secret"

db_instance_endpoint:
    resolvers:
    - "datastore"
    - "output"    

db_instance_port:
    resolvers:
    - "datastore"
    - "output"

# ----------
# admin user
# ----------
admin_login_username:
    resolvers:
    - "datastore"
    - "secret"

admin_login_password:
    resolvers:
    - "datastore"
    - "secret"

admin_email:
    resolvers:
    - "datastore"    

admin_first_name:
    resolvers:
    - "datastore"

admin_last_name:
    resolvers:
    - "datastore"

# ---------------
# client database
# ---------------
db_username:
    resolvers:
    - "datastore"
    - "secret"
    
db_password:
    resolvers:
    - "datastore"
    - "secret"

db_database:
    resolvers:
    - "datastore"

# -------
# service
# -------
php_version:
    resolvers:
    - "datastore"

php_suffix:
    resolvers:
    - "datastore"