---
# -----------------
# database instance
# -----------------
db_instance_username:
    resolvers:
    - datastore: {}
    - secret:
        index: "username"

db_instance_password:
    resolvers:
    - datastore: {}
    - secret:
        index: "password"

db_instance_endpoint:
    resolvers:
    - datastore: {}

db_instance_port:
    resolvers:
    - datastore: {}    

# ----------
# admin user
# ----------
admin_login_username:
    resolvers:
    - datastore: {}
    - secret:
        index: "username"

admin_login_password:
    resolvers:
    - datastore: {}
    - secret:
        index: "password"

admin_email:
    resolvers:
    - datastore: {}   

admin_first_name:
    resolvers:
    - datastore: {}

admin_last_name:
    resolvers:
    - datastore: {}

# ---------------
# client database
# ---------------
db_username:
    resolvers:
    - datastore: {}
    - secret:
        index: "username"
    
db_password:
    resolvers:
    - datastore: {}
    - secret:
        index: "password"

db_database:
    resolvers:
    - datastore: {}

# -------
# service
# -------
php_version:
    resolvers:
    - datastore: {}

php_suffix:
    resolvers:
    - datastore: {}