# This is a basic workflow to help you get started with Actions

name: Actions
on: pull_request
jobs:
    phplint:
        name: PHP Lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: michaelw90/PHP-Lint@master
    php-codesniffer:
        name: PHP CS
        runs-on: ubuntu-latest
        # You may pin to the exact commit or the version.
        # uses: pipeline-components/php-codesniffer@e3341450afba37fab4275b31f041646a26b2da9d
        steps:
            - name: Codesniffer
              uses: pipeline-components/php-codesniffer@v0.12.3
              with:
                  # Additional options
                  options: -s -p --colors --extensions=php
